### ISSUE TITLE
Crew wage per day for MS/CP doesn't always work

### ISSUE THREAD

**Issue by avizek-NOAA** [nwfsc-fram/FishEyeApp#29]

**Comment by melinashak-noaa** [comment]
Seems like there is something odd going on with AVE_MED2, the variable used to store median, mean, total for different stats. This is a shared variable so that could be the issues, but seems like it gets set somewhere randomly and is screwing everything up. To fix this, created a separate crewStat variable and used this instead of AVE_MED2
